from turtle import *
from random import randint
def play():
    speed(0)
    for step in range(11):
        write(step)
        right(90)
        forward(160)    
        penup()
        backward(160)
        left(90)
        forward(20)
        pendown()
    penup()
    goto(60,20)
    write("TURTLE RACE")
    goto(230,-50)
    right(90)
    write("F")
    goto(230,-60)
    write("I")
    goto(230,-70)
    write("N")
    goto(230,-80)
    write("I")
    goto(230,-90)
    write("S")
    goto(230,-100)
    write("H")
    goto(0,0)
    ada=Turtle()
    ada.color("red")
    ada.shape("turtle")
    ada.penup()
    ada.goto(-20,-20)
    adb=Turtle()
    adb.color("blue")
    adb.shape("turtle")
    adb.penup()
    adb.goto(-20,-60)
    adc=Turtle()
    adc.color("black")
    adc.shape("turtle")
    adc.penup()
    adc.goto(-20,-100)
    add=Turtle()
    add.color("green")
    add.shape("turtle")
    add.penup()
    add.goto(-20,-140)
    ada.pendown()
    adb.pendown()
    adc.pendown()
    add.pendown()
    for turn in range(70):
        ada.forward(randint(1,5))
        adb.forward(randint(1,5))
        adc.forward(randint(1,5))
        add.forward(randint(1,5))
